### ISSUE TITLE
no stdout log on Error thrown

### ISSUE THREAD

**Issue by franvala** [AntonelliLab/raxmlGUI#81]
Autogenerated report:
```json
{
  "message": "Exited with code 1. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 1. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/franc/AppData/Local/Temp/1TRvvn3aWQvg0gGFGmxVg2qxlQm/resources/app.asar/build/electron.js:1:11366)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 121 -p 929 -N 100 -m GTRGAMMA -O -n Otidea_Etrechy_ITS_aligned3juin18.tre -s \"E:\\aMonMycoseq\\Otidea\\Otidea Etrechy ITS aligned3juin18.fas\" -w \"E:\\aMonMycoseq\\Otidea\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.2
Electron 6.0.2
win32 10.0.17763
Locale: fr

**Comment by jtklein** [comment]
Thank you for your error report @franvala! I am not sure what happened in your run that was throwing this error. We would need some time to find out what it is about.
@danieledler : There are some double backslashes in the command line call, can this be the original problem that caused the error, or is this something that can happen when formatting the github error report?

**Comment by danieledler** [comment]
Yes the double backslash is for formatting, to escape the special characters within the string. The problem here is that it halts when spawning the RAxML binary without giving any explanation, so I think we need to add some tests to narrow down the issue, for example trying to create a file within the actual path or run a test binary that we know always works etc. Have to come back to this later.
